---
# ansible_role_system_nfs/tasks/main.yml
# Author: MTO 
# Description: Main file for ansible_role_system_nfs
#
- name: "MAIN - Display system, os, version and release" 
  debug: 
    msg: "ROLE ansible_role_system_nfs | SYSTEM {{ inventory_hostname }} | OS {{ ansible_distribution }} | VERSION {{ ansible_distribution_version }} | RELEASE {{ ansible_distribution_release }}"

- name: "MAIN - Include OS-specific variables."
  include_vars: 
    file: "{{ ansible_os_family | lower }}.yml"

- name: "MAIN - Ensure NFS utilities are installed."
  package: 
    name: nfs-utils 
    state: present

- name: "MAIN - Ensure rpcbind is running as configured."
  service:
    name: rpcbind
    state: "{{ system_nfs_rpcbind_state }}"
    enabled: "{{ system_nfs_rpcbind_enabled }}"

- name: "MAIN - Ensure directories to export exist."
  file: 
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ system_nfs_exports }}"

- name: "MAIN - Copy exports file."
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: "MAIN - Ensure nfs is running."
  service: 
    name: "{{ system_nfs_server_daemon }}" 
    state: started 
    enabled: yes
  when: (system_nfs_exports is defined and system_nfs_exports|length)